[[headers]]
  for = "/calculadora/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
